### ISSUE TITLE
Pip install of pyke or pyke v3 also known as pyke3 for Kelpler "Can I use it?" More direct links to orginal Pyke and Pyke3 files

### ISSUE THREAD

**Issue by sprinteroz** [keiffster/knowledge-y#1]
Hi @keiffster and All,
I have been looking around and found the link to pyke and pyke3 downloads but was looking for a later version see if I could find a pip install release of pyke3 as i'm using python 3.6
[ Link to pyke and pyke3 downloads](https://sourceforge.net/projects/pyke/files/pyke/1.1.1/)

Pip install of pyke or pyke v3 also known as pyke3 but do not know if it is a reverent find at all
[github.com PyKE](https://github.com/KeplerGO/PyKE)
[pyke.keplerscience.org](http://pyke.keplerscience.org/en/latest/)

**Comment by keiffster** [comment]
That's a very different project to Pyke I reference. The one you found is an image processing library where as the one I am using is basically Prolog in Python which allows forward and backward chaining of knowledge bases or facts

So rather than write aiml to process knowledge you establish it as a set of facts and let prolog do what's it's designed to do

**Comment by sprinteroz** [comment]
Thanks @keiffster,
I found a easy way to install it: pip install http://downloads.sourceforge.net/pyke/pyke-1.1.1.zip

**Comment by keiffster** [comment]
That’s great news, I’ll update the documentation for knowledge-y

It’s been several years since I did commercial prolog dev so just spending some r&d time working out how it works and how it will work with program-y but it’s looking promising and opens a wealth of capabilities for knowledge processing

K

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630
